DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    completed TINYINT(1) NOT NULL DEFAULT 0

);

