DROP TABLE IF EXISTS TASKS;

CREATE TABLE TASKS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    completed TINYINT(1) NOT NULL DEFAULT 0

);

